# Azure DevOps Pipeline for Python (hello.py)

trigger:
- main   # runs pipeline on push to main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Checkout source code from GitHub
- checkout: self
  displayName: 'Checkout source code'

# Step 2: Set up Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'   # you can change to 3.10 or 3.11
    addToPath: true
  displayName: 'Set up Python'

# Step 3: Install dependencies (requirements.txt if exists)
- script: |
    python -m pip install --upgrade pip
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  displayName: 'Install dependencies'

# Step 4: Run hello.py
- script: |
    python hello.py
  displayName: 'Run hello.py'

# Step 5: (Optional) Run tests if you add test_*.py files
- script: |
    pytest --maxfail=1 --disable-warnings -q || echo "No tests found"
  displayName: 'Run tests'
